[package]
name = "inline-const"
version = "0.0.1"
authors = ["Ralf Jung <post+crates@ralfj.de>"]
readme = "README.md"
repository = "https://github.com/RalfJung/inline-const"
edition = "2018"

[dependencies]
